steps:
# Clone the repository.
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - '--depth'
  - '1'
  - https://github.com/ithunter101/menu-app.git

# Build and tag the image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/digital-display-menu/version1', './menu-app/django']

# Publish the image to Container Registry.
images: ['gcr.io/digital-display-menu/version1']