# Generated by Django 2.1.4 on 2022-06-05 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('cast_id', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('orientation', models.BooleanField()),
                ('style', models.BooleanField()),
                ('content', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'screen',
                'ordering': ['id'],
            },
        ),
    ]
