# Generated by Django 2.1.4 on 2022-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0003_remove_screen_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='orientation',
            field=models.BooleanField(choices=[(1, 'Landscape'), (2, 'Portrait')], default=1),
        ),
        migrations.AlterField(
            model_name='screen',
            name='style',
            field=models.BooleanField(choices=[(1, 'Normal'), (2, 'White Background')], default=1),
        ),
        migrations.AlterField(
            model_name='screen',
            name='type',
            field=models.BooleanField(choices=[(1, 'Menu'), (2, 'Media')], default=1),
        ),
    ]
