# Generated by Django 2.1.4 on 2022-06-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0004_auto_20220605_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='orientation',
            field=models.BooleanField(choices=[(0, 'Landscape'), (1, 'Portrait')], default=0),
        ),
        migrations.AlterField(
            model_name='screen',
            name='style',
            field=models.BooleanField(choices=[(0, 'Normal'), (1, 'White Background')], default=0),
        ),
        migrations.AlterField(
            model_name='screen',
            name='type',
            field=models.BooleanField(choices=[(0, 'Menu'), (1, 'Media')], default=0),
        ),
    ]
