# Generated by Django 2.1.4 on 2022-06-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0005_auto_20220605_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='orientation',
            field=models.CharField(choices=[('landscape', 'Landscape'), ('portrait', 'Portrait')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screen',
            name='style',
            field=models.CharField(choices=[('normal', 'Normal'), ('white', 'White Background')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screen',
            name='type',
            field=models.CharField(choices=[('menu', 'Menu'), ('media', 'Media')], max_length=20),
        ),
    ]
