# Generated by Django 2.1.4 on 2022-06-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0006_auto_20220605_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=100)),
                ('arrangeable', models.BooleanField()),
            ],
            options={
                'db_table': 'category',
                'ordering': ['id'],
            },
        ),
    ]
