# Generated by Django 2.1.4 on 2022-06-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='start_on_new',
            field=models.BooleanField(default=False),
        ),
    ]
