# Generated by Django 2.1.4 on 2022-06-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0008_category_start_on_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='media',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
