# Generated by Django 2.2 on 2022-06-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0009_auto_20220606_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='start_on_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='screen',
            name='media',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
