# Generated by Django 2.2 on 2022-06-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuapi', '0011_auto_20220615_0644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='category',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
